/**
 * generate — кодогенератор метаданных Angular-компонентов.
 *
 * Читает manifest.ts из каждой папки компонентов, прогоняет дескриптор через
 * useInputs / useOutputs и генерирует `generated/<name>.metadata.ts`: массивы
 * имён входов и выходов для декоратора и абстрактный класс `T<Имя>Outputs`,
 * который типизирует выходы.
 *
 * Класс нужен строгой проверке шаблона: она читает выход как поле класса, а
 * эмиттеры ставит `TComponentBase` по массиву имён. Поля класса — `declare`:
 * они только объявляют тип (`TOutputEmitter` — по фабрике дескриптора из
 * манифеста и полному имени события), в рантайме их нет, и эмиттер базы ничто
 * не затирает. Декоратор `@Directive` обязателен: класс стоит в цепочке
 * наследования компонента, и на классе без декоратора компилятор обрывает
 * метаданные базы — вход `ctrl` пропал бы из шаблона потребителя
 * (`[ctrl]="btn"` — NG8002).
 *
 * Запуск: node --import tsx/esm src/codegen/generate.ts
 *   (или через скрипт в package.json: "generate": "tsx src/codegen/generate.ts")
 *
 * Сгенерированные файлы — артефакты сборки. НЕ редактировать вручную.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import * as prettier from 'prettier'
import { collectManifests } from './collect-manifests'
import { useInputs } from '../adapter/common/useInputs'
import { useOutputs } from '../adapter/common/useOutputs'

function toPascalCase(str: string): string {
	return str.replace(/(^\w|-\w)/g, (g) => g.replace('-', '').toUpperCase())
}

/**
 * Приводит вывод к тому же виду, что даёт `npm run format`.
 *
 * Иначе генератор и prettier — два писателя одних файлов с разным мнением о
 * кавычках и переносах: формат-прогон по репозиторию переписывает generated,
 * а CI сравнивает вывод generate с закоммиченным и падает на дрейфе, которого
 * по сути нет.
 */
async function format(content: string, filePath: string): Promise<string> {
	const config = await prettier.resolveConfig(filePath, { editorconfig: true })

	return prettier.format(content, { ...config, filepath: filePath })
}

async function generate(): Promise<void> {
	const manifests = await collectManifests()

	if (manifests.length === 0) {
		console.warn('⚠️  No manifests found in components/')
		return
	}

	const generatedDir = path.resolve(import.meta.dirname, '../generated')

	if (!fs.existsSync(generatedDir)) {
		fs.mkdirSync(generatedDir, { recursive: true })
	}

	for (const { name, folder, descriptor: descriptorFn } of manifests) {
		const descriptor = descriptorFn()
		const inputs = useInputs(descriptor)
		const outputs = useOutputs(descriptor)
		const constName = toPascalCase(name)

		const content = [
			'// Auto-generated by @soldy-ui/angular codegen. DO NOT EDIT.',
			`import { Directive } from '@angular/core'`,
			`import type { IEntity } from '@soldy-ui/core'`,
			`import { TComponentBase, type TOutputEmitter } from '../adapter/runtime'`,
			`import type { descriptor } from '../components/${folder}/manifest'`,
			'',
			`export const ${constName}Inputs = ${JSON.stringify(inputs)} as const`,
			`export const ${constName}Outputs = ${JSON.stringify(outputs.map(([output]) => output))} as const`,
			'',
			'/**',
			` * Типы выходов ${constName} для строгой проверки шаблона: эмиттеры ставит`,
			` * \`TComponentBase\` по \`${constName}Outputs\`, поля их только объявляют.`,
			' */',
			'@Directive({ standalone: true })',
			`export abstract class T${constName}Outputs<TInstance extends IEntity> extends TComponentBase<TInstance> {`,
			...outputs.map(
				([output, event]) =>
					`declare readonly ${output}: TOutputEmitter<typeof descriptor, ${JSON.stringify(event)}>`,
			),
			'}',
			'',
		].join('\n')

		const filePath = path.join(generatedDir, `${name}.metadata.ts`)

		fs.writeFileSync(filePath, await format(content, filePath))
		console.log(`✅  Generated ${filePath}`)
	}

	console.log(`\n${manifests.length} files generated.`)
}

generate().catch((err) => {
	console.error(err)
	process.exit(1)
})
