/**
 * generate — кодогенератор метаданных Angular-компонентов.
 *
 * Читает manifest.ts из каждой папки компонентов, прогоняет дескриптор через
 * useInputs / useOutputs и генерирует `generated/<name>.metadata.ts`.
 *
 * Запуск: node --import tsx/esm src/codegen/generate.ts
 *   (или через скрипт в package.json: "generate": "tsx src/codegen/generate.ts")
 *
 * Сгенерированные файлы — артефакты сборки. НЕ редактировать вручную.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'
import { collectManifests } from './collect-manifests'
import { useInputs } from '../adapter/common/useInputs'
import { useOutputs } from '../adapter/common/useOutputs'

function toPascalCase(str: string): string {
	return str.replace(/(^\w|-\w)/g, (g) => g.replace('-', '').toUpperCase())
}

async function generate(): Promise<void> {
	const manifests = await collectManifests()

	if (manifests.length === 0) {
		console.warn('⚠️  No manifests found in components/')
		return
	}

	const generatedDir = path.resolve(import.meta.dirname, '../generated')

	if (!fs.existsSync(generatedDir)) {
		fs.mkdirSync(generatedDir, { recursive: true })
	}

	for (const { name, descriptor: descriptorFn } of manifests) {
		const descriptor = descriptorFn()
		const inputs = useInputs(descriptor)
		const outputs = useOutputs(descriptor)
		const constName = toPascalCase(name)

		const content = [
			'// Auto-generated by @soldy/ui-angular codegen. DO NOT EDIT.',
			`export const ${constName}Inputs = ${JSON.stringify(inputs)} as const`,
			`export const ${constName}Outputs = ${JSON.stringify(outputs)} as const`,
			'',
		].join('\n')

		const filePath = path.join(generatedDir, `${name}.metadata.ts`)

		fs.writeFileSync(filePath, content)
		console.log(`✅  Generated ${filePath}`)
	}

	console.log(`\n${manifests.length} files generated.`)
}

generate().catch((err) => {
	console.error(err)
	process.exit(1)
})
