export { TScrollerViewportPlugin } from './viewport.plugin'
export { resolveEdges } from './edges'
export type { TEdgesOptions, TScrollerEdges } from './edges'
export { resolveFocusShift } from './focus'
export type { TFocusShiftOptions, TInlineSpan, TScrollerViewportPluginEvents } from './types'
