export { useAdapter } from './useAdapter'
export type { TAngularBinding } from './useAdapter'
export { bindOutput, bindInput, buildInitialState } from './useSyncProps'
export { bindEvents } from './useSyncEvents'
export { TAngularComponentBase } from './angular-component.base'
