export * from './item/types'
export { default as TTabsItem } from './item/item.class'
export { TTabsItemCollectionFacade } from './item/facade'
export * from './content'
export * from './types'
export { TTabs } from './tabs.class'
export * from './collection'
